openapi: 3.0.0
info:
  title: DP
  version: 1.0.0
servers:
  - url: http://{{url}}
paths:
  /api/getAllUsersSki:
    get:
      tags:
        - default
      summary: getAllUsersSki
      parameters:
        - name: ''
          in: header
          schema:
            type: string
        - name: user
          in: query
          schema:
            type: string
          example: '{{userID}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/:
    get:
      tags:
        - default
      summary: Test GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Test POST
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                Key:
                  type: string
                  example: Value
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
